image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # Explicitly set environment variables for the build process
    - export VITE_ENVIRONMENT=$VITE_ENVIRONMENT
    - export VITE_ANALYTICAL_URL_PRODUCTION=$VITE_ANALYTICAL_URL_PRODUCTION
    - export VITE_ANALYTICAL_URL_DEVELOPMENT=$VITE_ANALYTICAL_URL_DEVELOPMENT
    - export VITE_DOCRETR_URL_DEVELOPMENT=$VITE_DOCRETR_URL_DEVELOPMENT
    - export VITE_DOCRETR_API_KEY_DEVELOPMENT=$VITE_DOCRETR_API_KEY_DEVELOPMENT
    - export VITE_KRONOS_URL_PRODUCTION=$VITE_KRONOS_URL_PRODUCTION
    - export VITE_KRONOS_URL_DEVELOPMENT=$VITE_KRONOS_URL_DEVELOPMENT
    - export VITE_KRONOS_API_KEY_PRODUCTION=$VITE_KRONOS_API_KEY_PRODUCTION
    - export VITE_KRONOS_API_KEY_DEVELOPMENT=$VITE_KRONOS_API_KEY_DEVELOPMENT
    - echo $VITE_KRONOS_API_KEY_DEVELOPMENT # Check if the variable is set correctly
    # Install dependencies and build
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # Include the built files
      - node_modules/ # Include node_modules to avoid re-installing
  only:
    - main

deploy:
  stage: deploy
  only:
    - main # Deploy only from the 'main' branch
  script:
    # Re-export environment variables in the deploy stage (if necessary)
    - export VITE_ENVIRONMENT=$VITE_ENVIRONMENT
    - export VITE_ANALYTICAL_URL_PRODUCTION=$VITE_ANALYTICAL_URL_PRODUCTION
    - export VITE_ANALYTICAL_URL_DEVELOPMENT=$VITE_ANALYTICAL_URL_DEVELOPMENT
    - export VITE_DOCRETR_URL_DEVELOPMENT=$VITE_DOCRETR_URL_DEVELOPMENT
    - export VITE_DOCRETR_API_KEY_DEVELOPMENT=$VITE_DOCRETR_API_KEY_DEVELOPMENT
    - export VITE_KRONOS_URL_PRODUCTION=$VITE_KRONOS_URL_PRODUCTION
    - export VITE_KRONOS_URL_DEVELOPMENT=$VITE_KRONOS_URL_DEVELOPMENT
    - export VITE_KRONOS_API_KEY_PRODUCTION=$VITE_KRONOS_API_KEY_PRODUCTION
    - export VITE_KRONOS_API_KEY_DEVELOPMENT=$VITE_KRONOS_API_KEY_DEVELOPMENT
    - echo $VITE_KRONOS_URL_DEVELOPMENT
    # Install dependencies and deploy with Firebase
    - npm install
    - npm install -g firebase-tools
    - echo "Deploying to Firebase with token $FIREBASE_TOKEN"
    # Deploy using Firebase CLI, ensure token is set
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --project sop-generator
  dependencies:
    - build
  variables:
    FIREBASE_TOKEN: $FIREBASE_TOKEN # Ensure this is added to your GitLab CI/CD variables
  artifacts:
    paths:
      - dist/ # Carry over the dist files
      - node_modules/ # Carry over node_modules
