image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    VITE_ENVIRONMENT: $VITE_ENVIRONMENT
    VITE_ANALYTICAL_URL_PRODUCTION: $VITE_ANALYTICAL_URL_PRODUCTION
    VITE_ANALYTICAL_URL_DEVELOPMENT: $VITE_ANALYTICAL_URL_DEVELOPMENT
    VITE_DOCRETR_URL_DEVELOPMENT: $VITE_DOCRETR_URL_DEVELOPMENT
    VITE_DOCRETR_API_KEY_DEVELOPMENT: $VITE_DOCRETR_API_KEY_DEVELOPMENT
    VITE_KRONOS_URL_PRODUCTION: $VITE_KRONOS_URL_PRODUCTION
    VITE_KRONOS_URL_DEVELOPMENT: $VITE_KRONOS_URL_DEVELOPMENT
    VITE_KRONOS_API_KEY_PRODUCTION: $VITE_KRONOS_API_KEY_PRODUCTION
    VITE_KRONOS_API_KEY_DEVELOPMENT: $VITE_KRONOS_API_KEY_DEVELOPMENT
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # Include the built files
      - node_modules/ # Include node_modules to avoid re-installing
  only:
    - main

# test:
#   stage: test
#   script:
#     - echo "Test stage passed!"
#   when: always # This will always pass the test stage

deploy:
  stage: deploy
  only:
    - main # Deploy only from the 'main' branch
  script:
    - npm install
    - npm install -g firebase-tools
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --project sop-generator
  dependencies:
    - build
  artifacts:
    paths:
      - dist/ # Carry over the dist files
      - node_modules/ # Carry over node_modules

