stages:
  - build
  - test
  - deploy

variables:
  FIREBASE_TOKEN: $FIREBASE_TOKEN # Ensure this is added to your GitLab CI/CD variables
  VITE_ENVIRONMENT: $VITE_ENVIRONMENT
  VITE_ANALYTICAL_URL_PRODUCTION: $VITE_ANALYTICAL_URL_PRODUCTION
  VITE_ANALYTICAL_URL_DEVELOPMENT: $VITE_ANALYTICAL_URL_DEVELOPMENT
  VITE_DOCRETR_URL_DEVELOPMENT: $VITE_DOCRETR_URL_DEVELOPMENT
  VITE_DOCRETR_API_KEY_DEVELOPMENT: $VITE_DOCRETR_API_KEY_DEVELOPMENT
  VITE_KRONOS_URL_PRODUCTION: $VITE_KRONOS_URL_PRODUCTION
  VITE_KRONOS_URL_DEVELOPMENT: $VITE_KRONOS_URL_DEVELOPMENT
  VITE_KRONOS_API_KEY_PRODUCTION: $VITE_KRONOS_API_KEY_PRODUCTION
  VITE_KRONOS_API_KEY_DEVELOPMENT: $VITE_KRONOS_API_KEY_DEVELOPMENT

build:
  stage: build
  image: node:18 # Use Node.js 18
  before_script: # Generate a .env file for the firebase deployment
    - echo "VITE_ENVIRONMENT=$VITE_ENVIRONMENT" > .env
    - echo "VITE_ANALYTICAL_URL_PRODUCTION=$VITE_ANALYTICAL_URL_PRODUCTION" >> .env
    - echo "VITE_ANALYTICAL_URL_DEVELOPMENT=$VITE_ANALYTICAL_URL_DEVELOPMENT" >> .env
    - echo "VITE_DOCRETR_URL_DEVELOPMENT=$VITE_DOCRETR_URL_DEVELOPMENT" >> .env
    - echo "VITE_DOCRETR_API_KEY_DEVELOPMENT=$VITE_DOCRETR_API_KEY_DEVELOPMENT" >> .env
    - echo "VITE_KRONOS_URL_PRODUCTION=$VITE_KRONOS_URL_PRODUCTION" >> .env
    - echo "VITE_KRONOS_URL_DEVELOPMENT=$VITE_KRONOS_URL_DEVELOPMENT" >> .env
    - echo "VITE_KRONOS_API_KEY_PRODUCTION=$VITE_KRONOS_API_KEY_PRODUCTION" >> .env
    - echo "VITE_KRONOS_API_KEY_DEVELOPMENT=$VITE_KRONOS_API_KEY_DEVELOPMENT" >> .env
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # Include the built files
      - node_modules/ # Include node_modules to avoid re-installing
      - .env # Include the .env file if needed for deployment
  only:
    - main

test:
  stage: test
  image: node:18 # Ensuring the same Node version
  script:
    - echo "Test stage passed!"
  artifacts:
    paths:
      - dist/ # Include the built files
      - node_modules/ # Include node_modules for consistency
      - .env # Include .env if needed for testing
  when: always # This will always pass the test stage

deploy:
  stage: deploy
  image: node:18 # Ensure Node.js 18 for deployment
  only:
    - main # Deploy only from the 'main' branch
  script:
    - echo "Deploy stage starting..."
    - npm install -g firebase-tools
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --project sop-generator
  dependencies:
    - build
  artifacts:
    paths:
      - dist/ # Carry over the dist files
      - node_modules/ # Carry over node_modules
      - .env # Carry over the .env file if needed for deployment
