image: node:18

stages:
  - build
  - deploy

variables:
  FIREBASE_TOKEN: $FIREBASE_TOKEN # Ensure this is added to your GitLab CI/CD variables
  VITE_ENVIRONMENT: $VITE_ENVIRONMENT
  VITE_ANALYTICAL_URL_PRODUCTION: $VITE_ANALYTICAL_URL_PRODUCTION
  VITE_ANALYTICAL_URL_DEVELOPMENT: $VITE_ANALYTICAL_URL_DEVELOPMENT
  VITE_DOCRETR_URL_DEVELOPMENT: $VITE_DOCRETR_URL_DEVELOPMENT
  VITE_DOCRETR_API_KEY_DEVELOPMENT: $VITE_DOCRETR_API_KEY_DEVELOPMENT
  VITE_KRONOS_URL_PRODUCTION: $VITE_KRONOS_URL_PRODUCTION
  VITE_KRONOS_URL_DEVELOPMENT: $VITE_KRONOS_URL_DEVELOPMENT
  VITE_KRONOS_API_KEY_PRODUCTION: $VITE_KRONOS_API_KEY_PRODUCTION
  VITE_KRONOS_API_KEY_DEVELOPMENT: $VITE_KRONOS_API_KEY_DEVELOPMENT

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ # Include the built files
      - node_modules/ # Include node_modules to avoid re-installing
  only:
    - main

# test:
#   stage: test
#   script:
#     - echo "Test stage passed!"
#   when: always # This will always pass the test stage

deploy:
  stage: deploy
  only:
    - main # Deploy only from the 'main' branch
  script:
    - echo "Deploy stage starting..."
    - echo "Creating .env file..."
    - echo "VITE_ENVIRONMENT=${VITE_ENVIRONMENT}" > .env
    - echo "VITE_ANALYTICAL_URL_PRODUCTION=${VITE_ANALYTICAL_URL_PRODUCTION}" >> .env
    - echo "VITE_ANALYTICAL_URL_DEVELOPMENT=${VITE_ANALYTICAL_URL_DEVELOPMENT}" >> .env
    - echo "VITE_DOCRETR_URL_DEVELOPMENT=${VITE_DOCRETR_URL_DEVELOPMENT}" >> .env
    - echo "VITE_DOCRETR_API_KEY_DEVELOPMENT=${VITE_DOCRETR_API_KEY_DEVELOPMENT}" >> .env
    - echo "VITE_KRONOS_URL_PRODUCTION=${VITE_KRONOS_URL_PRODUCTION}" >> .env
    - echo "VITE_KRONOS_URL_DEVELOPMENT=${VITE_KRONOS_URL_DEVELOPMENT}" >> .env
    - echo "VITE_KRONOS_API_KEY_PRODUCTION=${VITE_KRONOS_API_KEY_PRODUCTION}" >> .env
    - echo "VITE_KRONOS_API_KEY_DEVELOPMENT=${VITE_KRONOS_API_KEY_DEVELOPMENT}" >> .env
    - npm install
    - npm install -g firebase-tools
    - firebase deploy --only hosting --token $FIREBASE_TOKEN --project sop-generator
  dependencies:
    - build
  artifacts:
    paths:
      - dist/ # Carry over the dist files
      - node_modules/ # Carry over node_modules

