stages:
  - build
  - deploy

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.8.0-debug
    entrypoint: [ "" ]
  variables:
    VERSION: $CI_COMMIT_SHORT_SHA
    IS_MAIN: "False"
    ENVIRONMENT: "DEVELOPMENT"
    KEYCLOAK_CLIENT_ID: $VITE_KEYCLOAK_CLIENT_ID_DEVELOPMENT
    KEYCLOAK_REALM: $VITE_KEYCLOAK_REALM_DEVELOPMENT
    KEYCLOAK_URL: $VITE_KEYCLOAK_URL_DEVELOPMENT
    KRONOS_API_KEY: $VITE_KRONOS_API_KEY_DEVELOPMENT
    KRONOS_URL: $VITE_KRONOS_URL_DEVELOPMENT
    MAESTRO_URL: $VITE_MAESTRO_URL_DEVELOPMENT
  only:
    refs:
      - develop
  script:
    - if [ -z "$TARGET" ]; then DOCKERFILE=Dockerfile; SUFFIX=""; else DOCKERFILE="$TARGET.Dockerfile"; SUFFIX="-$TARGET"; fi;
    - mkdir -p /kaniko/.docker && echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - GODEBUG="http2client=0" /kaniko/executor
      --context .
      --compressed-caching=false
      --destination $CI_REGISTRY_IMAGE:$VERSION
      --build-arg VERSION=$VERSION
      --build-arg IS_MAIN=$IS_MAIN
      --build-arg ENVIRONMENT=$ENVIRONMENT
      --build-arg KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
      --build-arg KEYCLOAK_REALM=$KEYCLOAK_REALM
      --build-arg KEYCLOAK_URL=$KEYCLOAK_URL
      --build-arg KRONOS_API_KEY=$KRONOS_API_KEY
      --build-arg KRONOS_URL=$KRONOS_URL
      --build-arg MAESTRO_URL=$MAESTRO_URL

build unstable:
  extends: .build

build release:
  extends: .build
  variables:
    VERSION: $CI_COMMIT_TAG
    IS_MAIN: "True"
    ENVIRONMENT: "PRODUCTION"
    KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID_PRODUCTION
    KEYCLOAK_REALM: $KEYCLOAK_REALM_PRODUCTION
    KEYCLOAK_URL: $KEYCLOAK_URL_PRODUCTION
    KRONOS_API_KEY: $KRONOS_API_KEY_PRODUCTION
    KRONOS_URL: $KRONOS_URL_PRODUCTION
    MAESTRO_URL: $MAESTRO_URL_PRODUCTION
  only:
    refs:
      - tags

build mf:
  extends: .build
  variables:
    VERSION: ${CI_COMMIT_TAG}-mf
    IS_MAIN: "True"
    ENVIRONMENT: "PRODUCTION"
    KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID_MF
    KEYCLOAK_REALM: $KEYCLOAK_REALM_MF
    KEYCLOAK_URL: $KEYCLOAK_URL_MF
    KRONOS_API_KEY: $KRONOS_API_KEY_MF
    KRONOS_URL: $KRONOS_URL_MF
    MAESTRO_URL: $MAESTRO_URL_MF
  only:
    refs:
      - tags
  when: manual

.deploy:
  stage: deploy
  image: registry.gitlab.com/promethistai/system/deployer:211222
  variables:
    KUBE_CONTEXT: promethistai-projects/ciirc-projects/selfservice/kronos:ciirc-aks
    NAMESPACE: develop
    NAME: maestro-admin
    NAME_SUFFIX: ""
    VERSION: $CI_COMMIT_SHORT_SHA
    BASE_DOMAIN: promethist.dev
  only:
    refs:
      - develop
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - /bin/sh deploy/prepare-namespace.sh $NAMESPACE
    - helm upgrade
      --install
      --namespace $NAMESPACE
      --set namespace=$NAMESPACE
      --set name=$NAME
      --set nameSuffix=$NAME_SUFFIX
      --set version=$VERSION
      --set app.image.name=$CI_REGISTRY_IMAGE
      --set app.image.tag=$VERSION
      --set baseDomain=$BASE_DOMAIN
      --reset-values
      --debug
      $NAME deploy/app

deploy unstable:
  extends: .deploy

deploy release:
  extends: .deploy
  variables:
    NAMESPACE: default
    VERSION: $CI_COMMIT_TAG
    BASE_DOMAIN: promethist.ai
  only:
    refs:
      - tags

deploy mf:
  extends: .deploy
  variables:
    KUBE_CONTEXT: promethistai-projects/ciirc-projects/selfservice/devops:mf-aks
    NAMESPACE: default
    NAME_SUFFIX: mf
    VERSION: ${CI_COMMIT_TAG}-mf
    BASE_DOMAIN: promethist.dev
  only:
    refs:
      - tags
  when: manual
