stages:
  - build
  - deploy

build unstable:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.8.0-debug
    entrypoint: [ "" ]
  only:
    refs:
      - development
  script:
    - if [ -z "$TARGET" ]; then DOCKERFILE=Dockerfile; SUFFIX=""; else DOCKERFILE="$TARGET.Dockerfile"; SUFFIX="-$TARGET"; fi;
    - mkdir -p /kaniko/.docker && echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - GODEBUG="http2client=0" /kaniko/executor
      --context .
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --compressed-caching=false
      --build-arg VERSION=$CI_COMMIT_SHORT_SHA
      --build-arg IS_MAIN="False"
      --force

build release:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.8.0-debug
    entrypoint: [ "" ]
  only:
    refs:
      - tags
  except:
    - /^(!main).+@/
  script:
    - if [ -z "$TARGET" ]; then DOCKERFILE=Dockerfile; SUFFIX=""; else DOCKERFILE="$TARGET.Dockerfile"; SUFFIX="-$TARGET"; fi;
    - mkdir -p /kaniko/.docker && echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - GODEBUG="http2client=0" /kaniko/executor
      --context .
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --compressed-caching=false
      --build-arg VERSION=$CI_COMMIT_TAG
      --build-arg IS_MAIN="True"

deploy unstable:
  stage: deploy
  image: registry.gitlab.com/promethistai/system/deployer:211222
  variables:
    NAME: selfservice-react
  only:
    refs:
      - development
  script:
    - kubectl config use-context $CI_PROJECT_NAMESPACE/kronos:ciirc-aks
    - /bin/sh deploy/prepare-namespace.sh develop
    - helm upgrade
      --install
      --namespace develop
      --set namespace=develop
      --set version=$CI_COMMIT_SHORT_SHA
      --set app.image.name=$CI_REGISTRY_IMAGE
      --set app.image.tag=$CI_COMMIT_SHORT_SHA
      --set imagePullPolicy=Always
      --set baseDomain=promethist.dev
      --set secretsName=$NAME-develop
      --set name=$NAME
      --reset-values
      --debug
      $NAME deploy/app

deploy release:
  stage: deploy
  image: registry.gitlab.com/promethistai/system/deployer:211222
  variables:
    NAME: selfservice-react
  only:
    refs:
      - tags
  except:
    - /^(!main).+@/
  script:
    - kubectl config use-context $CI_PROJECT_NAMESPACE/kronos:ciirc-aks
    - /bin/sh deploy/prepare-namespace.sh default
    - helm upgrade
      --install
      --namespace default
      --set namespace=default
      --set version=$CI_COMMIT_REF_NAME
      --set app.image.name=$CI_REGISTRY_IMAGE
      --set app.image.tag=$CI_COMMIT_REF_NAME
      --set imagePullPolicy=Always
      --set baseDomain=promethist.ai
      --set secretsName=$NAME
      --set name=$NAME
      --reset-values
      --debug
      $NAME deploy/app
