FROM node:18-alpine

# Install requirements
WORKDIR /app
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Env vars required for build
ARG VITE_ENVIRONMENT
ARG VITE_KRONOS_URL_DEVELOPMENT
ARG VITE_KRONOS_API_KEY_DEVELOPMENT
ARG VITE_KRONOS_URL_PRODUCTION
ARG VITE_KRONOS_API_KEY_PRODUCTION
ARG VITE_MAESTRO_URL_DEVELOPMENT
ARG VITE_MAESTRO_URL_PRODUCTION
ARG VITE_KEYCLOACK_URL
ARG VITE_KEYCLOACK_REALM
ARG VITE_KEYCLOACK_CLIENT_ID
ARG VITE_KEYCLOACK_DEVELOPMENT_CLIENT_ID
ARG VITE_KEYCLOACK_PRODUCTION_CLIENT_ID

# Build the React app
RUN npm run build

# Serve the built app
CMD ["npm", "run", "preview"]

EXPOSE 8080
