namespace: develop
name: selfservice-react
version: 0.0.1

hostName: maestro
baseDomain: promethist.dev
clusterIssuer: letsencrypt
ingressClassName: nginx
replicaCount: 1
secretsName: selfservice-react-develop

app:
  image:
    name: registry.gitlab.com/promethistai-projects/ciirc-projects/selfservice/selfservice_react
    tag: latest
  port: 8080
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
git:
  commit: short_sha
  ref: branch_or_tag
service:
  app:
    port: 8080
  type: ClusterIP
