namespace: develop
name: maestro-admin
version: 0.0.1

baseDomain: promethist.dev
clusterIssuer: letsencrypt
ingressClassName: nginx
replicaCount: 1

app:
  image:
    name: registry.gitlab.com/promethistai-projects/ciirc-projects/selfservice/selfservice_react
    tag: latest
  port: 8080
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
git:
  commit: short_sha
  ref: branch_or_tag
service:
  app:
    port: 8080
  type: ClusterIP
