interface ImportMetaEnv {
  VITE_ENVIRONMENT: "DEVELOPMENT" | "PRODUCTION"; // Specify possible values for VITE_ENVIRONMENT

  VITE_ANALYTICAL_URL_PRODUCTION: string;
  VITE_ANALYTICAL_URL_DEVELOPMENT: string;

  VITE_DOCRETR_URL_DEVELOPMENT: string;
  VITE_DOCRETR_API_KEY_DEVELOPMENT: string;

  VITE_KRONOS_URL_PRODUCTION: string;
  VITE_KRONOS_URL_DEVELOPMENT: string;
  VITE_KRONOS_API_KEY_PRODUCTION: string;
  VITE_KRONOS_API_KEY_DEVELOPMENT: string;

  VITE_KEYCLOAK_URL: string;
  VITE_KEYCLOAK_REALM: string;
  VITE_KEYCLOAK_CLIENT_ID: string;
  VITE_KEYCLOAK_CLIENT_ID_PRODUCTION: string;
  VITE_KEYCLOAK_CLIENT_ID_DEVELOPMENT: string;
  VITE_MAESTRO_URL_PRODUCTION: string;
  VITE_MAESTRO_URL_DEVELOPMENT: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
